### ISSUE TITLE
Malware warning on Windows 10 21H2

### ISSUE THREAD

**Issue by mbrezu** [PhoenixofForce/Ludum_Dare_51#1]
Hi,

I got a malware warning about your RAR download (https://github.com/PhoenixofForce/Ludum_Dare_51/releases/download/v1.1.1/SpeedBarberv1.1.1.rar). Unfortunately, the Windows UI for choosing what to do is suboptimal to say the least, so I did not get a chance to force the file extraction and compare to the files from the ZIP (which don't trigger any warning). I gave up after a few attempts :-|

This is a screenshot with the threat detected:

![image](https://user-images.githubusercontent.com/1485/193991204-8a0fd2be-19d6-4a8c-b58c-0613272cb942.png)

It might be just an artifact of the RAR archiver you used, I would just remove the RAR archive just in case.

**Comment by mbrezu** [comment]
I left a Github issue since it seems more private than a comment on the LD51 page of the game. Nice game!

**Comment by PhoenixofForce** [comment]
Hey,

thank you for letting us know. 
My windows doesnt give a malware warning. 
So I would guess, some people will and some wont get this warning. This is why i am keeping the .rar uploaded.
And in case the .rar fails, there is still the zip-File.

And also thanks for playing :)
